# Generated by Django 4.0.3 on 2022-03-15 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_code', models.CharField(blank=True, max_length=300, null=True)),
                ('employee_designation', models.CharField(blank=True, choices=[('SOFTWARE_ENGINEER', 'softwareEngineer'), ('SOFTWARE_DEVELOPER', 'softwareDeveloper'), ('SYSTEM_ENGINEER', 'systemEngineer'), ('ACCOUNTANT', 'accountant'), ('HR', 'hr')], max_length=100, null=True)),
                ('employee_department', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
